//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductBoxing
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoxDetail
    {
        public int BoxDetailID { get; set; }
        public Nullable<int> BoxMasterID { get; set; }
        public string LabelNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
